Fix error messages not showing up as intended.

diff --git a/scripts/nxt_send b/scripts/nxt_send
--- a/scripts/nxt_send
+++ b/scripts/nxt_send
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-set -e
+#set -e
 
 if [ ! $# -ge 1 ]
 then
@@ -16,9 +16,6 @@ NEXTTOOL_BINARY=`which nexttool 2>/dev/null || true`
 ([ -n "${NEXTTOOL_BINARY}" ] && [ -x "${NEXTTOOL_BINARY}" ]) || \
 	(echo "Error: nexttool binary cannot be executed." && exit 1)
 
-# Test if at least one nxt brick has been found.
-([ -n "`${NEXTTOOL_BINARY} -listbricks`" ]) ||  \
-	(echo "Error: No nxt brick found." && exit 1)
 
 # Send all specified files to the brick through usb.
 while [ $# -gt 0 ]; do
@@ -26,8 +23,13 @@ while [ $# -gt 0 ]; do
 	([ -e $1 ] && [ -r $1 ]) || \
 		(echo "Error: file \"$1\" cannot be read." && exit 1)
 
+	# Test if at least one nxt brick has been found.
+	([ -n "`${NEXTTOOL_BINARY} -listbricks`" ]) ||  \
+		(echo "Error: No nxt brick found." && exit 1)
+
 	# Send the file on the brick.
-	${NEXTTOOL_BINARY} /COM=usb -download="$1"
+	(${NEXTTOOL_BINARY} /COM=usb -download="$1") || \
+		(echo "Error: could not send file \"$1\" on brick." && exit 1)
 
 	# Check if the file is on the brick.
 	([ -n "`${NEXTTOOL_BINARY} /COM=usb -listfiles=\"$(basename $1)\" `" ]) || \
